CREATE TABLE [dbo].[Device]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ArdMAC] NVARCHAR(50) NOT NULL, 
    [minTemp] INT NOT NULL DEFAULT 0, 
    [maxTemp] INT NOT NULL DEFAULT 10, 
    [minHum] INT NOT NULL DEFAULT 0, 
    [maxHum] INT NOT NULL DEFAULT 10, 
    [sound] TINYINT NOT NULL DEFAULT 1, 
    [light] TINYINT NOT NULL DEFAULT 1
)
